[package]
name = "sample-ws-rs"
version = "0.1.0"
authors = ["4832cl0n <4_832cl0n@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.1"
rand = "0.8.2"